### ISSUE TITLE
Cannot create Custom objects

### ISSUE THREAD

**Issue by aphe** [SwiftKitz/Storez#13]
I try to create some custom objects,

```swift
struct StorezArray {
    var arrStr: [String]
}

extension StorezArray: UserDefaultsConvertible {
    typealias UserDefaultsType = String
    
    var encodeForUserDefaults: StorezArray.UserDefaultsType? {
        return arrStr.joined(separator: ";")
    }
    
    static func decode(userDefaultsValue value: StorezArray.UserDefaultsType) -> StorezArray? {
        return self.init(arrStr: value.components(separatedBy: ";"))
    }
}
```

but xcode always says

`Type 'StorezArray' does not conform to protocol 'UserDefaultsConvertible'`

even though i add the protocol stub

**Comment by Mazyod** [comment]
Hiya!
Can you try using `NSString` instead of `String`? UserDefaultsSupportedType is just a typealias for NSCoding, which Swift String doesn’t support.

We could explore supporting Codable for Swift types in the future!

**Comment by aphe** [comment]
yes, my bad not seeing what UserDefaultsSupportedType first.

thank you for your answer.
