### ISSUE TITLE
the newest version build failed in carthage

### ISSUE THREAD

**Issue by strangeliu** [SwiftKitz/Storez#6]
build failed in carthage and when i build in Xcode i get the incurrent headers.
the season is like this:
The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
warning: no umbrella header found for target 'Storez-ios', module map will not be generated
warning: no umbrella header found for target 'Storez-ios', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild -workspace ~/Carthage/Checkouts/Storez/Storez.xcworkspace -scheme Storez-ios -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
--- xcodebuild: WARNING: Unable to open project file '~/Carthage/Checkouts/Storez/Playground/Playground.playground' in workspace '~/Carthage/Checkouts/Storez/Storez.xcworkspace'.
*\* CLEAN FAILED **

**Comment by Mazyod** [comment]
Thank you, I'll deal with it asap

**Comment by Mazyod** [comment]
v2.0.2 released! I tested it with Carthage, and seems to work.
